version: "3"

services:
    nizouba_mysql:
        image: mysql:5.7.17
        ports:
            - "3307:3307"
        volumes:
            - "./docker-mysql/share/:/share/"
            - "./docker-mysql/db/:/docker-entrypoint-initdb.d/:ro"
            - "./docker-mysql/master/lib/:/var/lib/mysql/"
            - "./docker-mysql/master/log/:/var/log/mysql/"
            - "./docker-mysql/master/conf.d/:/etc/mysql/mysql.conf.d/"
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=123456
    nizouba_redis:
       image: redis:3.2
       ports:
         - 6379:6379
       volumes:
         - ./docker-redis/conf/redis.conf:/etc/redis/redis.conf
       command: redis-server /etc/redis/redis.conf