version: "3"

services:
    nizouba_mysql:
        image: mysql:5.7.17
        ports:
            - "3307:3307"
        volumes:
            - "./docker-mysql/share/:/share/"
            - "./docker-mysql/db/:/docker-entrypoint-initdb.d/:ro"
            - "./docker-mysql/master/lib/:/var/lib/mysql/"
            - "./docker-mysql/master/log/:/var/log/mysql/"
            - "./docker-mysql/master/conf.d/:/etc/mysql/mysql.conf.d/"
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=123456

    nizouba_nginx:
      image: nginx:1.11.6-alpine
      command:
        - /bin/sh
        - -c
        - |
          mkdir -p /usr/local/upload/es-test
          nginx -g 'daemon off;'

      ports:
        - 4444:4444
      volumes:
        - "./docker-nginx/conf.d:/etc/nginx/conf.d"
        - "./docker-nginx/log:/var/log/nginx"

