spring:
  datasource:
    username: zwxbest
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/xunwu
  thymeleaf:
    cache: false
server:
  port: 8082



